#! /bin/sh
case "$1" in
    -keep)
	shift
	;;
    *)
	: > debuglog
	: > accesslog
	;;
esac
./client.py $* -q
rm -f nohup.out
sleep 1
# temporary until DNS catches up
url="-u http://63.142.188.184/"
nohup ./server.py $url -t debuglog -l accesslog $* &
sleep 1
cat nohup.out
